### ISSUE TITLE
What differentiates mixtus?

### ISSUE THREAD

**Issue by polarathene** [traefik/mixtus#2]
I found this when looking into `structor`, but I'm not sure what problem `mixtus` is solving or if it's just an internal tool for Traefik?

Was this preferred over using Github Actions? Or perhaps it came about before Traefik switched over to using Github workflow for CI? I see the latest commit message in Jan 15 was "Goodbye Travis", and that around that time Traefik adopted a Github workflow to build docs too.

Is there an advantage of using `mixtus` vs the deploy action I'm using below?

```yml
jobs:
  deploy:
    name: 'Deploy Docs'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: 'Deploy to Github Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
```
